### ISSUE TITLE
Serial port close method

### ISSUE THREAD

**Issue by destar77** [godsharp/GodSharp.SerialPort#2]
I saw serial port close method like this `if (!serialPort.IsOpen) serialPort.Close();`.
correct me if I am wrong. the port need to close if the port is at open state or close state?

**Comment by seayxu** [comment]
`serialPort.IsOpen` is `true` mean that is opened

**Comment by destar77** [comment]
So the code is wrong checking `if  (!serialPort.IsOpen) serialPort.Close();` is wrong at close method

**Comment by seayxu** [comment]
You are right,this is a mistake,thank you.
