### ISSUE TITLE
只能在Program中正常使用？放到form中或者写成类调用都无法readData

### ISSUE THREAD

**Issue by remixjc** [godsharp/GodSharp.SerialPort#3]
只能在Program中正常使用？放到form中或者写成类调用都无法readData

**Comment by seayxu** [comment]
还没遇到过，能给各测试的吗

**Comment by remixjc** [comment]
就是现在在Program中可以，如果写个Application.Run(new Form()),在这个form中去调用这些代码就没办法receive数据

**Comment by seayxu** [comment]
你加群丢个测试的代码。
群号：467764581
点击链接加入群聊【GodSharp交流群】：https://jq.qq.com/?_wv=1027&k=D1SoDAWo

**Comment by remixjc** [comment]
`        /// <summary>
        /// 打开串口
        /// </summary>
        /// <param name="com">例如 COM3</param>
        /// <returns></returns>
        public void OpenCom(string com)
        {
            GodSerialPort gsp = new GodSerialPort(x =>
            {
                x.PortName = com;
                x.BaudRate = 19200;
            });
            gsp.UseDataReceived(true, (sp, bytes) =>
            {
                if (bytes != null && bytes.Length > 0)
                {
                    string buffer = string.Join(" ", GodSharp.SerialPort.Extensions.Extension.ToHexString(bytes));
                    Logs.LogHelper.Info("receive data:" + buffer);
                }
            });
            bool flag = gsp.Open();
        }`

**Comment by remixjc** [comment]
/// <summary>
        /// 打开串口
        /// </summary>
        /// <param name="com">例如 COM3</param>
        /// <returns></returns>
        public void OpenCom(string com)
        {
            GodSerialPort gsp = new GodSerialPort(x =>
            {
                x.PortName = com;
                x.BaudRate = 19200;
            });
            gsp.UseDataReceived(true, (sp, bytes) =>
            {
                if (bytes != null && bytes.Length > 0)
                {
                    string buffer = string.Join(" ", GodSharp.SerialPort.Extensions.Extension.ToHexString(bytes));
                    Logs.LogHelper.Info("receive data:" + buffer);
                }
            });
            bool flag = gsp.Open();
        }


如上方代码，通过调用的方式无法receive到数据，直接把方法中的代码copy到Program中才可以，不知道这个是我哪里出现问题了吗

**Comment by remixjc** [comment]
> 你加群丢个测试的代码。 群号：467764581 点击链接加入群聊【GodSharp交流群】：https://jq.qq.com/?_wv=1027&k=D1SoDAWo

咱有没有微信群啥的，QQ太大了，已经很久不用了

**Comment by seayxu** [comment]
你知道对象的作用域吗
```
    GodSerialPort gsp;

    /// <summary>
    /// 打开串口
    /// </summary>
    /// <param name="com">例如 COM3</param>
    /// <returns></returns>
    public void OpenCom(string com)
    {
        gsp = new GodSerialPort(x =>
        {
            x.PortName = com;
            x.BaudRate = 19200;
        });
        gsp.UseDataReceived(true, (sp, bytes) =>
        {
            if (bytes != null && bytes.Length > 0)
            {
                string buffer = string.Join(" ", GodSharp.SerialPort.Extensions.Extension.ToHexString(bytes));
                Logs.LogHelper.Info("receive data:" + buffer);
            }
        });
        bool flag = gsp.Open();
    }
```

**Comment by remixjc** [comment]
哦哦，明白了，多个串口就定义多个这种全局对象哈
